apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  jpetstore-ingress
spec:
  rules:
  - host: "jpetstore.20.81.78.25.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jpetstore
            port:
              number: 80
